### PR TITLE
Remove rgdal

### PR DESCRIPTION
**Pull request by evanamiesgalonski**
remove rgdal dependancy by storing hard copy of epsg descriptions instead of retrieving from `rgdal::make_EPSG()`.
update github action workflows

### CODE REVIEW

**Comment by evanamiesgalonski** [comment]
should be good to go now. had to disable some tests that required a google API key and therefore failed on actions

**Review by aylapear — CHANGES_REQUESTED** [review]
In terms of the google API key, if it makes sense to turn off in the actions that is fine but I can see before we added the API key as a secret and curious if we can do that again to get those tests passing. Also to turn the tests off in the action we should use the `skip_on_ci()` instead of commenting out the code.

**Comment by aylapear** [comment]
Also wondering if there is any information that should be supplied about the data set you supplied in the rds file. Like where we that info/data came from if we ever need to update the .rds file. This could be added to the data-raw.R script before the file is read in. I am not very familiar with epsg so not sure if it's standard and so providing info on where we got that is unneeded.

**Comment by evanamiesgalonski** [comment]
Good points, I'll add some info on the EPSG rds.

Thats interesting about the API key i wonder why the secret is no longer present/accessible. is the pointer for this key stored in the workflow file? i wonder if updating to the new template of the workflow is what broke it.

In the meantime ill send a built binary to Andrea so she can install from source and get poispkgs working.

**Comment by evanamiesgalonski** [comment]
Indeed, looks like the update to the workflow file blew away the secret. Restored now along with the tests. Added link to a resource for a EPSG codes in the documentation.

**Comment by aylapear** [comment]
The templates for the actions are general so when you update them you need to check if anything was special for the repo and add that part back in. It can be hard to tell sometimes a new version from the repo specific things.

**Review by aylapear — APPROVED** [review]
Thanks for making those changes, looks good to go.

**Pull request merged**
