### PR TITLE
Upkeep

### PR DESCRIPTION
**Pull request by dunkenwg**

### CODE REVIEW

**Comment by dunkenwg** [comment]
I'm getting a couple warnings when I run the tests locally:
```
Warning (test-load.R:16:3): can load multiple spatial files and files of a certain type
automatically selected the first layer in a data source containing more than one.
```
and 5 instances of:
```
Centroids not accurate for long/lat data.
```
Should I suppress these warnings or change the inputs to the functions in the test?

**Comment by joethorley** [comment]
Where possible it better to modify the code to avoid warnings - they may indicate problems in our code (unless the purpose of the code is to trigger the warnings). 
I'm assuming this is not the case? In the first instance does it make sense to set the active geometry (or is the function code turning off which is active)? And in theh second instance I think  `sf::st_set_agr(x, "constant")` might help. These are advance sf issues so it may require myself, Ayla or Seb to deal with.

**Review by joethorley — CHANGES_REQUESTED** [review]
Where possible it better to modify the code to avoid warnings - they may indicate problems in our code (unless the purpose of the code is to trigger the warnings).
I'm assuming this is not the case? In the first instance does it make sense to set the active geometry (or is the function code turning off which is active)? And in theh second instance I think sf::st_set_agr(x, "constant") might help. These are advance sf issues so it may require myself, Ayla or Seb to deal with.

**Comment by dunkenwg** [comment]
For the first warning, `ps_load_spatial()` is loading a .gpkg file with multiple layers and defaulting to the first layer.

For the second set of warnings, we are calling `ps_sfcs_centroid()` on WGS84 (longitude and latitude) data:
```
  pt <- readRDS(system.file("sf/pt.rds", package = "poisspatial")) %>%
    ps_sfcs_to_wgs84()
  cent.pt1 <- ps_sfcs_centroid(pt, sfc_names = "geometry")
```

Do you have any more advice on how I should tackle these warnings?

**Comment by joethorley** [comment]
For the second one I would add the following function call inside the function

x <- sf::st_set_agr(x, "constant")

**Comment by dunkenwg** [comment]
Unfortunately, that doesn't seem to be working

**Comment by dunkenwg** [comment]
@joethorley, would you be able to review this when you get a chance?

**Review by joethorley — APPROVED** [review]

**Pull request merged**
